name: gorelease

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  gorelease:
    runs-on: ubuntu-24.04
    env:
      # renovate: datasource=custom.goreleaser depName=goreleaser versioning=semver
      GORELEASER_VERSION: v2.11.1
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5
        with:
          go-version-file: go.mod
      - uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6
        with:
          args: release --clean
          version: ${{ env.GORELEASER_VERSION }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pull_request'
        uses: goreleaser/goreleaser-action@9c156ee8a17a598857849441385a2041ef570552 # v6
        with:
          args: release --clean --skip=publish --snapshot
          version: ${{ env.GORELEASER_VERSION }}
