name: gorelease

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  gorelease:
    runs-on: ubuntu-24.04
    env:
      # renovate: datasource=custom.goreleaser depName=goreleaser versioning=semver
      GORELEASER_VERSION: v2.12.6
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          fetch-depth: 0
      - uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
        with:
          go-version-file: go.mod
      - uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        if: github.event_name != 'pull_request'
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7
        with:
          args: release --clean
          version: ${{ env.GORELEASER_VERSION }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pull_request'
        uses: goreleaser/goreleaser-action@ec59f474b9834571250b370d4735c50f8e2d1e29 # v7
        with:
          args: release --clean --skip=publish --snapshot
          version: ${{ env.GORELEASER_VERSION }}
