name: gorelease

on:
  push:
    tags:
      - '*'

jobs:
  gorelease:
    runs-on: ubuntu-22.04
    env:
      # renovate: datasource=github-releases depName=goreleaser packageName=goreleaser/goreleaser versioning=semver
      GORELEASER_VERSION: v1.8.3
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags
      - uses: actions/setup-go@v5
        with:
          go-version: '1.18'
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --rm-dist
          version: ${{ env.GORELEASER_VERSION }}
