name: gorelease

on:
  pull_request:
  push:
    tags:
      - '*'

jobs:
  gorelease:
    runs-on: ubuntu-22.04
    env:
      # renovate: datasource=github-releases depName=goreleaser packageName=goreleaser/goreleaser versioning=semver
      GORELEASER_VERSION: v1.26.2
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name != 'pull_request'
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
          version: ${{ env.GORELEASER_VERSION }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'pull_request'
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean --skip=publish --snapshot
          version: ${{ env.GORELEASER_VERSION }}
