name: Release

on:
  pull_request:
    branches:
    - '!*'
  push:
    branches:
    - '!*'
    tags:
    - 'v*'

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: 1.12

    - name: Login to GCR
      env:
        GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
      run: |
        echo "$GCLOUD_AUTH" | \
          base64 --decode | \
          docker login -u _json_key --password-stdin https://asia.gcr.io

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: curl -sL https://git.io/goreleaser | bash
